import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"node:*",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: prod ? "silent" : "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	conditions: ["svelte", "browser"],
	plugins: [
		esbuildSvelte({
			preprocess: sveltePreprocess(),
			compilerOptions: { css: "injected" },
		}),
	],
});

if (prod) {
	const result = await context.rebuild();
	if (result.warnings.length > 0) {
		const formatted = await esbuild.formatMessages(result.warnings, {
			kind: "warning",
			color: process.stderr.isTTY,
		});
		for (const warning of formatted) process.stderr.write(warning);
	}
	const projectWarnings = result.warnings.filter((warning) => {
		const file = warning.location?.file?.replaceAll("\\", "/");
		return file?.startsWith("src/") || file?.includes("/src/");
	});
	if (projectWarnings.length > 0) {
		console.error(
			`production build rejected ${projectWarnings.length} project-authored Svelte warning(s)`,
		);
		process.exit(1);
	}
	await context.dispose();
} else {
	await context.watch();
}
